### ISSUE TITLE
Backpublish for Scala 3.0.0

### ISSUE THREAD

**Issue by julienrf** [scala/scala-parallel-collections#180]
May I request a release for Scala 3.0.0?

**Comment by SethTisue** [comment]
yes, I'll do that today

**Comment by SethTisue** [comment]
* [ ] wait for ScalaCheck to publish
* [ ] update the crossbuild
* [x] choose version number
  * v1.0.3, since we added `Automatic-Module-Name`
* [ ] tag the release
  * https://github.com/scala/scala-parallel-collections/releases/tag/v1.0.3
* [ ] wait for release build
  * https://travis-ci.com/github/scala/scala-parallel-collections/
* [ ] release the staging repos
  * http://oss.sonatype.org/#stagingRepositories
* [ ] artifacts on Maven Central
  * https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_3.0.0/1.0.3/
* [ ] readme updates? build.sbt updates?
  * none needed
